# Generated by Django 3.0.2 on 2025-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0002_auto_20200205_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Glucose_Random',
            new_name='customer_age',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Urea',
            new_name='engine_type',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Packed_cell_volume',
            new_name='gross_weight',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Serum_Creatine',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='White_blood_count',
            new_name='region_density',
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='subscription_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='turning_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='vehicle_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
