# Generated by Django 3.0.2 on 2025-07-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0003_auto_20250711_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckdmodel',
            name='subscription_length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ckdmodel',
            name='turning_radius',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ckdmodel',
            name='vehicle_age',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ckdmodel',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
